name: daily-metrics

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: tuc0w
          template: classic
          base: header, activity, community, metadata
          config_timezone: Europe/Berlin
          repositories_forks: yes

          # Isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_ignored: html, scss, arduino, kotlin, objective-c, css, twig
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 3000
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # WakaTime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 30
          plugin_wakatime_limit: 3
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: .user.login

          # Steam
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_API_TOKEN }}
          plugin_steam_user: ${{ secrets.STEAM_ID }}
          plugin_steam_achievements_limit: 3
          plugin_steam_games_limit: 1
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 1
          plugin_steam_sections: most-played, recently-played
